site_name: Projet Atténuation Laser
repo_url: https://github.com/OPTIQ-2025/laser-att

extra_css :
  - stylesheets/extra.css

nav:
  - Notre projet: index.md
  - Matériel et Librairies: materiel-et-librairies.md
  - Scripts python : scripts-python.md
  - Interfaces Moteur et Puissance-mètre: interfaces-moteur-&-puissance-mètre.md

theme:
  name : material
  features :
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - content.code.select

  palette:
    - scheme : slate
      toggle:
        icon : material/weather-sunny
        name : passer au mode jour
        primary : custom
        accent : custom
    
    - scheme : default
      toggle :
        icon : material/weather-night
        name : passer au mode nuit
        primary : custom
        accent : custom
  highlightjs: false

extra:
  highlight:
    theme: material

extra_css:
  - stylesheets/extra.css

markdown_extensions :
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      pygments_style: monokai
      noclasses: true
  - footnotes
  - attr_list
  - md_in_html
  - toc :
      permalink: true
      toc_depth: 1-3
      title: Table des matières
  - pymdownx.snippets:
      base_path: ["src", "docs"]
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline 
      pygments_lang_class: true
  - pymdownx.superfences

plugins:
  - include-markdown :
      base_path: docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OPTIQ-2025
  


